from TypeBase import *

EFI_CAPSULE_HEADER = [EFI_GUID, UINT32, UINT32, UINT32]
EFI_FIRMWARE_MANAGEMENT_CAPSULE_HEADER = [UINT32, UINT16, UINT16]
EFI_FIRMWARE_MANAGEMENT_CAPSULE_IMAGE_HEADER = [UINT32, EFI_GUID, UINT8, UINT8, UINT8, UINT8, UINT32, UINT32, UINT64]
FMP_PAYLOAD_HEADER = [UINT32, UINT32, UINT32, UINT32]