from TypeBase import *

EFI_FVB_ATTRIBUTES = UINT32
EFI_FV_BLOCK_MAP_ENTRY = [UINT32, UINT32]
EFI_FIRMWARE_VOLUME_HEADER = [UINT8] * 16 + [EFI_GUID, UINT64, UINT32, EFI_FVB_ATTRIBUTES, UINT16, UINT16, UINT16, UINT8, UINT8] + EFI_FV_BLOCK_MAP_ENTRY

EFI_FFS_INTEGRITY_CHECK = UINT16
EFI_FV_FILETYPE = UINT8
EFI_FFS_FILE_ATTRIBUTES = UINT8
EFI_FFS_FILE_STATE = UINT8

EFI_FFS_FILE_HEADER = [EFI_GUID, EFI_FFS_INTEGRITY_CHECK, EFI_FV_FILETYPE, EFI_FFS_FILE_ATTRIBUTES, UINT8, UINT8, UINT8, EFI_FFS_FILE_STATE]

EFI_FVH_SIGNATURE = EFI_SIGNATURE_32(ord('_'),ord('F'),ord('V'),ord('H'))
EFI_FVN_SIGNATURE_STR = "_FVH"